meal_plans/urls.py
from django.urls import path

from meal_plans.views import (
    MealPlanListView,
    MealPlanDetailView,
    MealPlanCreateView,
    MealPlanUpdateView,
    MealPlanDeleteView,
)

urlpatterns = [
    path("", MealPlanListView.as_view(), name="meals_list"),
    path("<int:pk>/", MealPlanDetailView.as_view(), name="meal_detail"),
    path("new/", MealPlanCreateView.as_view(), name="meal_new"),
    path("<int:pk>/edit/", MealPlanUpdateView.as_view(), name="meal_edit"),
    path("<int:pk>/delete/", MealPlanDeleteView.as_view(), name="meal_delete"),
]

scrumptious/urls.py
from django.contrib import admin
from django.urls import include, path, reverse_lazy
from django.views.generic.base import RedirectView
from django.contrib.auth import views as auth_views

urlpatterns = [
    path("meal_plans/", include("meal_plans.urls")),
    path("admin/", admin.site.urls),
    path("accounts/login/", auth_views.LoginView.as_view(), name="login"),
    path("accounts/logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("recipes/", include("recipes.urls")),
    path("tags/", include("tags.urls")),
    path(
        "",
        RedirectView.as_view(url=reverse_lazy("recipes_list")),
        name="home",
    ),
]

tags/urls.py
from django.urls import path

from tags.views import (
    TagListView,
    TagDeleteView,
    TagDetailView,
    TagCreateView,
    TagUpdateView,
)

urlpatterns = [
    path("", TagListView.as_view(), name="tags_list"),
    path("<int:pk>/", TagDetailView.as_view(), name="tag_detail"),
    path("<int:pk>/delete/", TagDeleteView.as_view(), name="tag_delete"),
    path("new/", TagCreateView.as_view(), name="tag_new"),
    path("<int:pk>/edit/", TagUpdateView.as_view(), name="tag_edit"),
]

meal_plans/models.py
from django.db import models
from django.conf import settings

USER_MODEL = settings.AUTH_USER_MODEL


class MealPlan(models.Model):
    name = models.CharField(max_length=125)
    date = models.DateField(auto_now_add=False)
    owner = models.ForeignKey(USER_MODEL, on_delete=models.CASCADE)
    recipes = models.ManyToManyField(
        "recipes.Recipe", related_name="meal_plans"
    )

    def __str__(self):
        return self.name

meal_plans/views.py
from django.shortcuts import redirect
from django.urls import reverse_lazy
from meal_plans.models import MealPlan
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin


class MealPlanListView(LoginRequiredMixin, ListView):
    model = MealPlan
    template_name = "meal_plans/list.html"
    paginate_by = 2

    def get_queryset(self):
        return MealPlan.objects.filter(owner=self.request.user)


class MealPlanDetailView(DetailView):
    model = MealPlan
    template_name = "meal_plans/detail.html"
    context_object_name = "mealplan_detail"

    def get_queryset(self):
        return MealPlan.objects.filter(owner=self.request.user)


class MealPlanCreateView(LoginRequiredMixin, CreateView):
    model = MealPlan
    template_name = "meal_plans/new.html"
    fields = ["name", "date", "recipes"]
    success_url = reverse_lazy("meals_list")

    def form_valid(self, form):
        plan = form.save(commit=False)
        plan.owner = self.request.user
        plan.save()
        form.save_m2m()
        return redirect("meal_detail", pk=plan.id)

    def get_queryset(self):
        return MealPlan.objects.filter(owner=self.request.user)

    def get_success_url(self) -> str:
        return reverse_lazy("meal_detail", args=[self.object.id])


class MealPlanUpdateView(LoginRequiredMixin, UpdateView):
    model = MealPlan
    template_name = "meal_plans/edit.html"
    fields = ["name", "date", "recipes"]
    success_url = reverse_lazy("meals_list")

    def get_queryset(self):
        return MealPlan.objects.filter(owner=self.request.user)

    def get_success_url(self) -> str:
        return reverse_lazy("meal_detail", args=[self.object.id])


class MealPlanDeleteView(LoginRequiredMixin, DeleteView):
    model = MealPlan
    template_name = "meal_plans/delete.html"
    success_url = reverse_lazy("meals_list")

    def get_queryset(self):
        return MealPlan.objects.filter(owner=self.request.user)

meal_plans/templates/meal_plans/delete.html
{% extends 'base.html' %}


{% block content %}
<main>
    <div class="delete-form">
        <form method="post">
            {% csrf_token %}
            <p>Are you sure you want to delete "{{ mealplan.name }}"?</p>
            {{ form.as_p }}
            <div>
                <button class="button">Delete</button>
            </div>
        </form>
    </div>
</main>
{% endblock content %}

meal_plans/templates/meal_plans/detail.html
{% extends 'base.html' %}


{% block content %}
<main class="recipe-detail">
    <div>
        <a href="{% url 'meal_edit' mealplan_detail.id %}">Edit</a>
        <a href="{% url 'meal_delete' mealplan_detail.id %}">Delete</a>
    </div>
    <h1>{{ mealplan_detail.name }}</h1>
    <p>
        Date on {{mealplan_detail.date }}
    </p>
</main>
{% endblock content %}

meal_plans/templates/meal_plans/edit.html
{% extends 'base.html' %}


{% block content %}
<main class="recipe-form">
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <div class="control">
            <button class="button">Update</button>
        </div>
    </form>
</main>
{% endblock content %}

meal_plans/templates/meal_plans/list.html
{% extends 'paginate.html' %}


{% block content %}
<main class="recipe-grid">
  {% for meal in mealplan_list %}
  <div class="recipe-card">
    <h2 class="recipe-card-title">
      <a href="{% url 'meal_detail' meal.pk %}">{{ meal.name }}</a>
    </h2>
    {% for recipe in meal.recipes.all %}
    <p>
      <a href="{% url 'recipe_detail' recipe.pk %}">{{recipe.name}}</a>
    </p>
    {% endfor %}
    <p>
      {{meal.date}}
    </p>
  </div>
  {% empty %}
  <div>
    <h1>No meals, yet</h1>
    <p>
      Would you like to
      <a href="{% url 'meal_new' %}">create</a>
      one?
    </p>
  </div>
  {% endfor %}
</main>
{% endblock content %}

meal_plans/templates/meal_plans/new.html
{% extends 'base.html' %}


{% block content %}
<main class="recipe-form">
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <div class="control">
            <button class="button">Create</button>
        </div>
    </form>
</main>
{% endblock content %}